---
title: "Lab 1"
author: "Maryanne Thangarajah"
date: "06/10/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Lab 1: Data Science I

**Link to github:** https://github.com/mthangarajah/Labs.git

```{r, warning=FALSE, message=FALSE}
# Loading all the neccessary packages
library(mdsr)
library(ggplot2)
library(dplyr)
library(scales)
library(devtools)
```


```{r, message=FALSE}
babyname <- make_babynames_dist() # Make the baby dataframe and assign to variable

babyname_df <- babyname # Create new variable by assigning previous dataframe


baby_percentdead <- # Assign new variable
  babyname_df %>% 
  group_by(sex, name) %>% # Group variables by sex and name
  summarise(totalpeople = sum(n), 
            percent_dead = (1 - (sum(est_alive_today)) /  sum(n))) %>%
  #Add new variable in dataframe from previous columns
  filter(totalpeople > 100000) %>% #Remove multiples of the same nam
  group_by(sex) %>% # Group by each sex
  top_n(10) # Get the top 10 names for each sex


ggplot(baby_percentdead, aes(reorder(name, percent_dead), y = percent_dead, fill =
                               sex)) + 
  # Create a plot using the dataframe above and reoder the data by name 
  # and the percent_dead in the x and y as the percent_dead
  # Fill the plot by sex
 
   geom_bar(stat = "identity",
           width = 0.85)  +
  # Create a bar plot with individual bars in the plot with spacing between bars
  
  coord_flip() + 
  # Flip the coordinates
  
  scale_fill_manual(values = c("#e1ad01", "#1C86EE")) +
  # Adding the colors to the bars for each sex
  
  geom_text(aes(label = percent(percent_dead, accuracy = 0.1)), size = 3.0, hjust = -0.05) +
  # Adding the labels to each bar as a percent, adjusting for size and position
  
  labs(title = "Deadest Names", 
       subtitle = "Estimated percentage of Americans with a given name born since \n        1900 who were dead as of Jan. 1, 2014") +
  # Add the title and subtitle to graph
  
  theme(
    # Update the theme in the graph
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    # Blank grid on plot
    legend.position = "none",
    # No legend on graph
    axis.ticks = element_blank(),
    # No ticks on the axis
    plot.background = element_blank(),
    # No background for the graph
    plot.title = element_text(face = "bold", hjust = -0.12),
    plot.subtitle = element_text(hjust = -0.28),
    # Positions for both the title and subtitle on graph
    # Create bolded title
    axis.text.x = element_blank()
    # No x-axis labelled
  ) +
  
  xlab(element_blank()) + 
  ylab(element_blank()) + 
  # No labels for both the x and y-axis
  
  # Expand the x-axis and y-axis to reducing spacing between x and y-axis
  scale_x_discrete(expand = expansion(mult = c(0, 0)))  + 
  scale_y_continuous(expand = expansion(mult = c(0, .07)))
```

